### ISSUE TITLE
Font-display:swap

### ISSUE THREAD

**Issue by dazecoop** [packaged-ui/fontawesome#1]
To help Chrome Lighthouse scores & overall speed, can `font-display:auto` be changed to `font-display:swap` within this file? -- https://raw.githubusercontent.com/packaged-ui/fontawesome/master/assets/css/all.min.css

There are 3 instances of font-display being used here.

Doing so improves Chrome Lighthouse score & very slight page rendering speed.

Thanks @bajb @TomK 👋

**Comment by bajb** [comment]
Hey @dazecoop

That file is copied from the font-awesome library, unmodified
https://github.com/FortAwesome/Font-Awesome/blob/master/css/all.min.css

You could easily replace the font-display in an overriding css, but we want to avoid modifying the content within the upstream package.
